title: "Troll Tales"
permalink: /:year/:month/:day/:title/

url: "https://www.troll-tales.ch"

wikilinks:
  attributes:
    enabled: true
  case:
    'lower case'
  css:
    exclude: []
    name:
      typed: 'typed'
      wiki: 'wiki-link'
      web: 'web-link'
      invalid_wiki: 'invalid-wiki-link'
      embed_container: 'embed-container'
      embed_title: 'embed-title'
      embed_content: 'embed-content'
      embed_link: 'embed-wiki-link'
      embed_image_container: 'embed-image-container'
      embed_image: 'embed-image'
  enabled: true
  exclude: []
